backend:
  name: github
  repo: Xutianlee/bird-website
  branch: main
  open_authoring: true
publish_mode: editorial_workflow

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "articles"
    label: "文章"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "日期", name: "date", widget: "datetime"}
      - {label: "内容", name: "body", widget: "markdown"}